# LOGS
LOGGING_LEVEL_ROOT: INFO
LOG_LEVEL: DEBUG
LOGGING_LOGSTASH_ENABLED: false
STREAMS_LOG_LEVEL: INFO

# KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_JAAS_ENABLED: false

# JAAS
APP_KAFKA_USER: username
APP_KAFKA_PASSWORD: password

# Postgres
APP_POSTGRESQL_HOST: localhost
APP_POSTGRESQL_PORT: 5432
APP_POSTGRESQL_USER: pguser
APP_POSTGRESQL_PASSWORD: pgpw
APP_POSTGRESQL_NAME: pgdb
