# LOGS
LOGGING_LEVEL_ROOT: INFO
LOG_LEVEL: DEBUG
LOGGING_LOGSTASH_ENABLED: false
STREAMS_LOG_LEVEL: INFO

# KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_JAAS_ENABLED: false

# JAAS
KAFKA_USER: username
KAFKA_PASSWORD: password

# Postgres
HOST_DB: localhost
PORT_DB: 5432
POSTGRES_USER: pguser
POSTGRES_PASSWORD: pgpw
POSTGRES_DB: pgdb
