# KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:29092

# Postgres
HOST_DB: localhost
PORT_DB: 5440
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres
POSTGRES_SCHEMA: image_manager


