# LOGS
LOGGING_LEVEL_ROOT: INFO
LOG_LEVEL: DEBUG
LOGGING_LOGSTASH_ENABLED: false
STREAMS_LOG_LEVEL: INFO

# KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:29092,localhost:29093,localhost:29094
REPLICAS: 3
PARTITIONS: 1

# Postgres
HOST_DB: localhost
PORT_DB: 5440
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres
POSTGRES_SCHEMA: public


