# LOGS
LOGGING_LEVEL_ROOT: INFO
LOG_LEVEL: DEBUG
LOGGING_LOGSTASH_ENABLED: false
STREAMS_LOG_LEVEL: INFO

# KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:9092,localhost:9093,localhost:9094
KAFKA_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_JAAS_ENABLED: false

# JAAS
KAFKA_USER: kafka
KAFKA_PASSWORD: password123

# Postgres
HOST_DB: localhost
PORT_DB: 5440
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres
POSTGRES_SCHEMA: public


