server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: liquibase/changelog.yaml

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group-id: ${IMAGE_MANAGER_GROUP_ID:image_manager_group}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
  properties:
    sasl:
      mechanism: PLAIN

  jaas:
    enabled: ${KAFKA_JAAS_ENABLED:true}
    login-module: org.apache.kafka.common.security.plain.PlainLoginModule
    options:
      username: ${KAFKA_USER:kafka}
      password: ${KAFKA_PASSWORD:password123}

springdoc:
  swagger-ui:
    path: /docs
