server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: liquibase/changelog.yaml

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    auto-offset-reset: earliest
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
  properties:
    sasl:
      mechanism: PLAIN
  listener:
    retry:
      enabled: false

  jaas:
    enabled: ${KAFKA_JAAS_ENABLED:true}
    login-module: org.apache.kafka.common.security.plain.PlainLoginModule
    options:
      username: ${KAFKA_USER:kafka}
      password: ${KAFKA_PASSWORD:password123}

springdoc:
  swagger-ui:
    path: /docs

kafka:
  topics:
    new-photos:
      name: ${NEW_PHOTOS:new.photos}
      groupId: ${NEW_PHOTOS_GROUP_ID:new.photos.group.id}
      dlq: ${NEW_PHOTOS_DLQ:new.photos.dlq}
    workers-results:
      name: ${WORKERS_RESULTS:workers.results}
      groupId: ${WORKERS_RESULTS_GROUP_ID:workers.results.group.id}
      dlq: ${WORKERS_RESULTS_DLQ:workers.results.dlq}
    audit:
      name: ${AUDIT_ERROR:agroscienceteam.audit.messages}

  partitions: ${PARTITIONS:1}
  replicas: ${REPLICAS:1}
