server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${APP_POSTGRESQL_HOST}:${APP_POSTGRESQL_PORT}/${APP_POSTGRESQL_NAME}?currentSchema=imagemanager"
    username: ${APP_POSTGRESQL_USER}
    password: ${APP_POSTGRESQL_PASSWORD}
  liquibase:
    change-log: liquibase/changelog.yaml

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    auto-offset-reset: earliest
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
  properties:
    sasl:
      mechanism: PLAIN
  jaas:
    enabled: ${KAFKA_JAAS_ENABLED:true}
    login-module: org.apache.kafka.common.security.plain.PlainLoginModule
    options:
      username: ${APP_KAFKA_USER:kafka}
      password: ${APP_KAFKA_PASSWORD:password123}
